SpringWoods_MapScripts::
	.byte 0


SpringWoods_BugCatcher::
# 4 "data/maps/SpringWoods/scripts.pory"
	trainerbattle_single TRAINER_SPRING_WOODS_BUG_CATCHER, SpringWoods_BugCatcher_Text_0, SpringWoods_BugCatcher_Text_1
# 9 "data/maps/SpringWoods/scripts.pory"
	msgbox SpringWoods_BugCatcher_Text_2, MSGBOX_AUTOCLOSE
	end


SpringWoods_Woman::
# 14 "data/maps/SpringWoods/scripts.pory"
	trainerbattle_single TRAINER_SPRING_WOODS_WOMAN, SpringWoods_Woman_Text_0, SpringWoods_Woman_Text_1
# 19 "data/maps/SpringWoods/scripts.pory"
	msgbox SpringWoods_Woman_Text_2, MSGBOX_AUTOCLOSE
	end


SpringWoods_Girl::
# 24 "data/maps/SpringWoods/scripts.pory"
	trainerbattle_single TRAINER_SPRING_WOODS_GIRL, SpringWoods_Girl_Text_0, SpringWoods_Girl_Text_1
# 29 "data/maps/SpringWoods/scripts.pory"
	msgbox SpringWoods_Girl_Text_2, MSGBOX_AUTOCLOSE
	end


SpringWoods_Picnicker::
# 34 "data/maps/SpringWoods/scripts.pory"
	trainerbattle_single TRAINER_SPRING_WOODS_PICNICKER, SpringWoods_Picnicker_Text_0, SpringWoods_Picnicker_Text_1
# 39 "data/maps/SpringWoods/scripts.pory"
	msgbox SpringWoods_Picnicker_Text_2, MSGBOX_AUTOCLOSE
	end


SpringWoods_BugCatcher_Text_0:
# 6 "data/maps/SpringWoods/scripts.pory"
	.string "Spring Woods have a great vibe!$"

SpringWoods_BugCatcher_Text_1:
# 7 "data/maps/SpringWoods/scripts.pory"
	.string "I can't even be mad, I'm enjoying the\n"
	.string "vibes here.$"

SpringWoods_BugCatcher_Text_2:
# 9 "data/maps/SpringWoods/scripts.pory"
	.string "The air is nice and cool in here, it's a\n"
	.string "really nice vibe.$"

SpringWoods_Woman_Text_0:
# 16 "data/maps/SpringWoods/scripts.pory"
	.string "The Pokemon here are really cute.$"

SpringWoods_Woman_Text_1:
# 17 "data/maps/SpringWoods/scripts.pory"
	.string "Not everyone can appreciate my tastes.$"

SpringWoods_Woman_Text_2:
# 19 "data/maps/SpringWoods/scripts.pory"
	.string "Sometimes it's nice to just be in\n"
	.string "nature.$"

SpringWoods_Girl_Text_0:
# 26 "data/maps/SpringWoods/scripts.pory"
	.string "My Pokemon will be strong!$"

SpringWoods_Girl_Text_1:
# 27 "data/maps/SpringWoods/scripts.pory"
	.string "Strength is built up over time...$"

SpringWoods_Girl_Text_2:
# 29 "data/maps/SpringWoods/scripts.pory"
	.string "I feel like I spend more time battling\n"
	.string "the desire to eat ice-cream than I do\l"
	.string "battling wild Pokemon.$"

SpringWoods_Picnicker_Text_0:
# 36 "data/maps/SpringWoods/scripts.pory"
	.string "Did you know that Springwood City is\n"
	.string "named after the Spring Woods?$"

SpringWoods_Picnicker_Text_1:
# 37 "data/maps/SpringWoods/scripts.pory"
	.string "My fun fact didn't distract you from\n"
	.string "winning.$"

SpringWoods_Picnicker_Text_2:
# 39 "data/maps/SpringWoods/scripts.pory"
	.string "Spring Woods are named after the spring\n"
	.string "that provides the water for the woods\l"
	.string "to propsper.$"
