OchreVale_Indoor_2_MapScripts::
	.byte 0


OcherVale_Indoor_2_Camper::
# 4 "data/maps/OchreVale_Indoor_2/scripts.pory"
	lockall
# 5 "data/maps/OchreVale_Indoor_2/scripts.pory"
	msgbox OcherVale_Indoor_2_Camper_Text_0, MSGBOX_NPC
# 6 "data/maps/OchreVale_Indoor_2/scripts.pory"
	releaseall
	return


OcherVale_Indoor_2_Picnicker::
# 10 "data/maps/OchreVale_Indoor_2/scripts.pory"
	lockall
# 11 "data/maps/OchreVale_Indoor_2/scripts.pory"
	msgbox OcherVale_Indoor_2_Picnicker_Text_0, MSGBOX_NPC
# 12 "data/maps/OchreVale_Indoor_2/scripts.pory"
	releaseall
	return


OcherVale_Indoor_2_Camper_Text_0:
# 5 "data/maps/OchreVale_Indoor_2/scripts.pory"
	.string "The quarry used to be a lot more active,\n"
	.string "but ever since the research started\l"
	.string "the actual excavation has taken a back\l"
	.string "seat.$"

OcherVale_Indoor_2_Picnicker_Text_0:
# 11 "data/maps/OchreVale_Indoor_2/scripts.pory"
	.string "My husband used to be one of the miners\n"
	.string "here, but since the mining has slowed\l"
	.string "right down he's gotten a lot more time\l"
	.string "to spend with me, which is nice.$"
