
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE 0
#define PARTNER_SCORCHED_CHAMBERS_EVELYNN 1
#define PARTNER_COUNT 2


#define PARTNER_STEVEN 1

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
