OchreVale_PokeMart_MapScripts::
	.byte 0


OchreVale_PokeMart_Youngster::
# 4 "data/maps/OchreVale_PokeMart/scripts.pory"
	lockall
# 5 "data/maps/OchreVale_PokeMart/scripts.pory"
	msgbox OchreVale_PokeMart_Youngster_Text_0, MSGBOX_NPC
# 6 "data/maps/OchreVale_PokeMart/scripts.pory"
	releaseall
	return


OchreVale_PokeMart_Scientist::
# 10 "data/maps/OchreVale_PokeMart/scripts.pory"
	lockall
# 11 "data/maps/OchreVale_PokeMart/scripts.pory"
	msgbox OchreVale_PokeMart_Scientist_Text_0, MSGBOX_NPC
# 12 "data/maps/OchreVale_PokeMart/scripts.pory"
	releaseall
	return


OchreVale_PokeMart_AquaGrunt::
# 16 "data/maps/OchreVale_PokeMart/scripts.pory"
	lockall
# 17 "data/maps/OchreVale_PokeMart/scripts.pory"
	msgbox OchreVale_PokeMart_AquaGrunt_Text_0, MSGBOX_NPC
# 18 "data/maps/OchreVale_PokeMart/scripts.pory"
	releaseall
	return


OchreVale_PokeMart_Youngster_Text_0:
# 5 "data/maps/OchreVale_PokeMart/scripts.pory"
	.string "Aw man, I'm 3 Poke-dollars short of a\n"
	.string "Lemonade...$"

OchreVale_PokeMart_Scientist_Text_0:
# 11 "data/maps/OchreVale_PokeMart/scripts.pory"
	.string "Do you think Awakenings work on\n"
	.string "humans? I could really use one right\l"
	.string "about now.$"

OchreVale_PokeMart_AquaGrunt_Text_0:
# 17 "data/maps/OchreVale_PokeMart/scripts.pory"
	.string "Oh...\nuh...\pDon't mind me,\nI was just wondering what\lTeam Magma was up to.$"
