DyecressTown_Indoor2_MapScripts::
	.byte 0


DyecressTown_Indoor2_OldWoman::
# 4 "data/maps/DyecressTown_Indoor2/scripts.pory"
	lockall
# 5 "data/maps/DyecressTown_Indoor2/scripts.pory"
	msgbox DyecressTown_Indoor2_OldWoman_Text_0, MSGBOX_NPC
# 6 "data/maps/DyecressTown_Indoor2/scripts.pory"
	releaseall
	return


DyecressTown_Indoor2_OldWoman_Text_0:
# 5 "data/maps/DyecressTown_Indoor2/scripts.pory"
	.string "My grandson likes to visit occasionally,\n"
	.string "but it can be pretty cumbersome\l"
	.string "getting through those pesky ledges.$"
