SpringwoodCity_Indoor_1_MapScripts::
	.byte 0


SpringwoodCity_Indoor_1_FatMan::
# 4 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	msgbox SpringwoodCity_Indoor_1_FatMan_Text_0, MSGBOX_NPC
	return


SpringwoodCity_Indoor_1_Man::
# 8 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	msgbox SpringwoodCity_Indoor_1_Man_Text_0, MSGBOX_NPC
	return


SpringwoodCity_Indoor_1_Woman::
# 12 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	msgbox SpringwoodCity_Indoor_1_Woman_Text_0, MSGBOX_NPC
	return


SpringwoodCity_Indoor_1_FatMan_Text_0:
# 4 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	.string "I booked a room on a high floor, but I\n"
	.string "forgot I was fat and now I don't want\l"
	.string "to have to walk up all the stairs...$"

SpringwoodCity_Indoor_1_Man_Text_0:
# 8 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	.string "I came to Springwood City hoping to\n"
	.string "become a pokemon trainer, but my\l"
	.string "girlfriend followed me here so now I\l"
	.string "can't.$"

SpringwoodCity_Indoor_1_Woman_Text_0:
# 12 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	.string "My boyfriend planned us a surprise trip\n"
	.string "to the city! It was such a surprise he\l"
	.string "didn't even tell me he was going!$"
