SpringwoodCity_Indoor_1_MapScripts::
	.byte 0


SpringwoodCity_Indoor_1_FatMan::
# 4 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	lockall
# 5 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	msgbox SpringwoodCity_Indoor_1_FatMan_Text_0, MSGBOX_NPC
# 6 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	releaseall
	return


SpringwoodCity_Indoor_1_Man::
# 10 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	lockall
# 11 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	msgbox SpringwoodCity_Indoor_1_Man_Text_0, MSGBOX_NPC
# 12 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	releaseall
	return


SpringwoodCity_Indoor_1_Woman::
# 16 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	lockall
# 17 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	msgbox SpringwoodCity_Indoor_1_Woman_Text_0, MSGBOX_NPC
# 18 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	releaseall
	return


SpringwoodCity_Indoor_1_FatMan_Text_0:
# 5 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	.string "I booked a room on a high floor, but I\n"
	.string "forgot I was fat and now I don't want\l"
	.string "to have to walk up all the stairs...$"

SpringwoodCity_Indoor_1_Man_Text_0:
# 11 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	.string "I came to Springwood City hoping to\n"
	.string "become a pokemon trainer, but my\l"
	.string "girlfriend followed me here so now I\l"
	.string "can't.$"

SpringwoodCity_Indoor_1_Woman_Text_0:
# 17 "data/maps/SpringwoodCity_Indoor_1/scripts.pory"
	.string "My boyfriend planned us a surprise trip\n"
	.string "to the city! It was such a surprise he\l"
	.string "didn't even tell me he was going!$"
