OchreVale_Indoor_3_MapScripts::
	.byte 0


OchreVale_Indoor_3_Woman::
# 4 "data/maps/OchreVale_Indoor_3/scripts.pory"
	lockall
# 5 "data/maps/OchreVale_Indoor_3/scripts.pory"
	msgbox OchreVale_Indoor_3_Woman_Text_0, MSGBOX_NPC
# 6 "data/maps/OchreVale_Indoor_3/scripts.pory"
	releaseall
	return


OchreVale_Indoor_3_Woman_Text_0:
# 5 "data/maps/OchreVale_Indoor_3/scripts.pory"
	.string "My boyfriend is researching the dirt\n"
	.string "here. I don't really understand what\l"
	.string "he's saying when he talks about it, but\l"
	.string "he looks so excited so I feel happy for\l"
	.string "him.$"
