SpringwoodCity_PokeMart_MapScripts::
	.byte 0


SpringwoodCity_PokeMart_Girl::
# 4 "data/maps/SpringwoodCity_PokeMart/scripts.pory"
	lockall
# 5 "data/maps/SpringwoodCity_PokeMart/scripts.pory"
	msgbox SpringwoodCity_PokeMart_Girl_Text_0, MSGBOX_NPC
# 6 "data/maps/SpringwoodCity_PokeMart/scripts.pory"
	releaseall
	return


SpringwoodCity_PokeMart_Girl_Text_0:
# 5 "data/maps/SpringwoodCity_PokeMart/scripts.pory"
	.string "I love the smell of new Pokeballs.$"
