Route9_MapScripts::
	.byte 0


Route9_Youngster::
# 4 "data/maps/Route9/scripts.pory"
	trainerbattle_single TRAINER_ROUTE9_YOUNGSTER, Route9_Youngster_Text_0, Route9_Youngster_Text_1
# 9 "data/maps/Route9/scripts.pory"
	msgbox Route9_Youngster_Text_2, MSGBOX_AUTOCLOSE
	end


Route9_Woman::
# 14 "data/maps/Route9/scripts.pory"
	trainerbattle_double TRAINER_ROUTE9_COUPLE, Route9_Woman_Text_0, Route9_Woman_Text_1, Route9_Woman_Text_2
# 20 "data/maps/Route9/scripts.pory"
	msgbox Route9_Woman_Text_3, MSGBOX_AUTOCLOSE
	end


Route9_Man::
# 25 "data/maps/Route9/scripts.pory"
	trainerbattle_double TRAINER_ROUTE9_COUPLE, Route9_Man_Text_0, Route9_Man_Text_1, Route9_Woman_Text_2
# 31 "data/maps/Route9/scripts.pory"
	msgbox Route9_Man_Text_2, MSGBOX_AUTOCLOSE
	end


Route9_RunnerF::
# 36 "data/maps/Route9/scripts.pory"
	trainerbattle_single TRAINER_ROUTE9_RUNNERF, Route9_RunnerF_Text_0, Route9_RunnerF_Text_1
# 41 "data/maps/Route9/scripts.pory"
	msgbox Route9_RunnerF_Text_2, MSGBOX_AUTOCLOSE
	end


Route9_RunnerM::
# 46 "data/maps/Route9/scripts.pory"
	trainerbattle_single TRAINER_ROUTE9_RUNNERM, Route9_RunnerM_Text_0, Route9_RunnerM_Text_1
# 51 "data/maps/Route9/scripts.pory"
	msgbox Route9_RunnerM_Text_2, MSGBOX_AUTOCLOSE
	end


Route9_Lady::
# 56 "data/maps/Route9/scripts.pory"
	trainerbattle_single TRAINER_ROUTE9_LADY, Route9_Lady_Text_0, Route9_Lady_Text_1
# 61 "data/maps/Route9/scripts.pory"
	msgbox Route9_Lady_Text_2, MSGBOX_AUTOCLOSE
	end


Route9_TuberM::
# 66 "data/maps/Route9/scripts.pory"
	trainerbattle_single TRAINER_ROUTE9_TUBERM, Route9_TuberM_Text_0, Route9_TuberM_Text_1
# 71 "data/maps/Route9/scripts.pory"
	msgbox Route9_TuberM_Text_2, MSGBOX_AUTOCLOSE
	end


Route9_TuberF::
# 76 "data/maps/Route9/scripts.pory"
	trainerbattle_single TRAINER_ROUTE9_TUBERF, Route9_TuberF_Text_0, Route9_TuberF_Text_1
# 81 "data/maps/Route9/scripts.pory"
	msgbox Route9_TuberF_Text_2, MSGBOX_AUTOCLOSE
	end


Route9_Fisherman::
# 86 "data/maps/Route9/scripts.pory"
	trainerbattle_single TRAINER_ROUTE9_FISHERMAN, Route9_Fisherman_Text_0, Route9_Fisherman_Text_1
# 91 "data/maps/Route9/scripts.pory"
	msgbox Route9_Fisherman_Text_2, MSGBOX_AUTOCLOSE
	end


Route9_Youngster_Text_0:
# 6 "data/maps/Route9/scripts.pory"
	.string "Hey! This is my cool Pokemon spot! Find\n"
	.string "your own!$"

Route9_Youngster_Text_1:
# 7 "data/maps/Route9/scripts.pory"
	.string "Well... Mum always said I should share...$"

Route9_Youngster_Text_2:
# 9 "data/maps/Route9/scripts.pory"
	.string "You better not find any cool Pokemon\n"
	.string "here before I do!$"

Route9_Woman_Text_0:
# 16 "data/maps/Route9/scripts.pory"
	.string "The beach here is a nice place to\n"
	.string "unwind.$"

Route9_Woman_Text_1:
# 17 "data/maps/Route9/scripts.pory"
	.string "My Boyfriend and I will wash away this\n"
	.string "loss in the sea.$"

Route9_Woman_Text_2:
# 18 "data/maps/Route9/scripts.pory"
	.string "You only have one Pokemon? That's sad.$"

Route9_Woman_Text_3:
# 20 "data/maps/Route9/scripts.pory"
	.string "I like the ocean, but I don't like the\n"
	.string "salt.$"

Route9_Man_Text_0:
# 27 "data/maps/Route9/scripts.pory"
	.string "My Girlfriend loves being at the beach!$"

Route9_Man_Text_1:
# 28 "data/maps/Route9/scripts.pory"
	.string "I'm happy if she's happy.$"

Route9_Man_Text_2:
# 31 "data/maps/Route9/scripts.pory"
	.string "It's a shame she's not in a bikini today.$"

Route9_RunnerF_Text_0:
# 38 "data/maps/Route9/scripts.pory"
	.string "The sand really gets my calves pumping!$"

Route9_RunnerF_Text_1:
# 39 "data/maps/Route9/scripts.pory"
	.string "Can't make any gains without a few\n"
	.string "losses along the way.$"

Route9_RunnerF_Text_2:
# 41 "data/maps/Route9/scripts.pory"
	.string "My legs are on fire!$"

Route9_RunnerM_Text_0:
# 48 "data/maps/Route9/scripts.pory"
	.string "Feel the cardio burn!$"

Route9_RunnerM_Text_1:
# 49 "data/maps/Route9/scripts.pory"
	.string "Yeah okay just ruin my workout why\n"
	.string "don't you...$"

Route9_RunnerM_Text_2:
# 51 "data/maps/Route9/scripts.pory"
	.string "There's this cute girl I'm trying to\n"
	.string "impress by getting fit.$"

Route9_Lady_Text_0:
# 58 "data/maps/Route9/scripts.pory"
	.string "I can smell the sea from here.$"

Route9_Lady_Text_1:
# 59 "data/maps/Route9/scripts.pory"
	.string "My tears taste salty like the sea...$"

Route9_Lady_Text_2:
# 61 "data/maps/Route9/scripts.pory"
	.string "I used to come to the beach with my\n"
	.string "mother, I miss her.$"

Route9_TuberM_Text_0:
# 68 "data/maps/Route9/scripts.pory"
	.string "SURPRISE!$"

Route9_TuberM_Text_1:
# 69 "data/maps/Route9/scripts.pory"
	.string "You weren't shocked enough!$"

Route9_TuberM_Text_2:
# 71 "data/maps/Route9/scripts.pory"
	.string "We like to hide and jump out to scare\n"
	.string "people.$"

Route9_TuberF_Text_0:
# 78 "data/maps/Route9/scripts.pory"
	.string "GOTCHA!$"

Route9_TuberF_Text_1:
# 79 "data/maps/Route9/scripts.pory"
	.string "Aw man I thought I got you...$"

Route9_TuberF_Text_2:
# 81 "data/maps/Route9/scripts.pory"
	.string "My hiding spot is better than his!$"

Route9_Fisherman_Text_0:
# 88 "data/maps/Route9/scripts.pory"
	.string "Ocean fishing always brings new\n"
	.string "encounters!$"

Route9_Fisherman_Text_1:
# 89 "data/maps/Route9/scripts.pory"
	.string "New doesn't necessarily mean good.$"

Route9_Fisherman_Text_2:
# 91 "data/maps/Route9/scripts.pory"
	.string "The Pokemon you find when fishing in\n"
	.string "the ocean is very different to those\l"
	.string "found in rivers.$"
