ScorchedChambers_MapScripts::
	.byte 0


ScorchedChambers_Hiker::
# 4 "data/maps/ScorchedChambers/scripts.pory"
	trainerbattle_single TRAINER_SCORCHED_CHAMBERS_HIKER, ScorchedChambers_Hiker_Text_0, ScorchedChambers_Hiker_Text_1
# 9 "data/maps/ScorchedChambers/scripts.pory"
	msgbox ScorchedChambers_Hiker_Text_2, MSGBOX_AUTOCLOSE
	end


ScorchedChambers_Picnicker::
# 14 "data/maps/ScorchedChambers/scripts.pory"
	trainerbattle_single TRAINER_SCORCHED_CHAMBERS_PICNICKER, ScorchedChambers_Picnicker_Text_0, ScorchedChambers_Picnicker_Text_1
# 19 "data/maps/ScorchedChambers/scripts.pory"
	msgbox ScorchedChambers_Picnicker_Text_2, MSGBOX_AUTOCLOSE
	end


ScorchedChambers_Guitarist::
# 24 "data/maps/ScorchedChambers/scripts.pory"
	trainerbattle_single TRAINER_SCORCHED_CHAMBERS_GUITARIST, ScorchedChambers_Guitarist_Text_0, ScorchedChambers_Guitarist_Text_1
# 29 "data/maps/ScorchedChambers/scripts.pory"
	msgbox ScorchedChambers_Guitarist_Text_2, MSGBOX_AUTOCLOSE
	end


ScorchedChambers_BugCatcher::
# 34 "data/maps/ScorchedChambers/scripts.pory"
	trainerbattle_single TRAINER_SCORCHED_CHAMBERS_BUG_CATCHER, ScorchedChambers_BugCatcher_Text_0, ScorchedChambers_BugCatcher_Text_1
# 39 "data/maps/ScorchedChambers/scripts.pory"
	msgbox ScorchedChambers_BugCatcher_Text_2, MSGBOX_AUTOCLOSE
	end


ScorchedChambers_Fisherman::
# 44 "data/maps/ScorchedChambers/scripts.pory"
	trainerbattle_single TRAINER_SCORCHED_CHAMBERS_FISHERMAN, ScorchedChambers_Fisherman_Text_0, ScorchedChambers_Fisherman_Text_1
# 49 "data/maps/ScorchedChambers/scripts.pory"
	msgbox ScorchedChambers_Fisherman_Text_2, MSGBOX_AUTOCLOSE
	end


ScorchedChambers_BlackBelt::
# 54 "data/maps/ScorchedChambers/scripts.pory"
	trainerbattle_single TRAINER_SCORCHED_CHAMBERS_BLACKBELT, ScorchedChambers_BlackBelt_Text_0, ScorchedChambers_BlackBelt_Text_1
# 59 "data/maps/ScorchedChambers/scripts.pory"
	msgbox ScorchedChambers_BlackBelt_Text_2, MSGBOX_AUTOCLOSE
	end


ScorchedChambers_BattleGirl::
# 64 "data/maps/ScorchedChambers/scripts.pory"
	trainerbattle_single TRAINER_SCORCHED_CHAMBERS_BATTLEGIRL, ScorchedChambers_BattleGirl_Text_0, ScorchedChambers_BattleGirl_Text_1
# 69 "data/maps/ScorchedChambers/scripts.pory"
	msgbox ScorchedChambers_BattleGirl_Text_2, MSGBOX_AUTOCLOSE
	end


ScorchedChambers_ExpertF::
# 74 "data/maps/ScorchedChambers/scripts.pory"
	trainerbattle_single TRAINER_SCORCHED_CHAMBERS_EXPERTF, ScorchedChambers_ExpertF_Text_0, ScorchedChambers_ExpertF_Text_1
# 79 "data/maps/ScorchedChambers/scripts.pory"
	msgbox ScorchedChambers_ExpertF_Text_2, MSGBOX_AUTOCLOSE
	end


ScorchedChambers_ExpertM::
# 84 "data/maps/ScorchedChambers/scripts.pory"
	trainerbattle_single TRAINER_SCORCHED_CHAMBERS_EXPERTM, ScorchedChambers_ExpertM_Text_0, ScorchedChambers_ExpertM_Text_1
# 89 "data/maps/ScorchedChambers/scripts.pory"
	msgbox ScorchedChambers_ExpertM_Text_2, MSGBOX_AUTOCLOSE
	end


ScorchedChambers_Camper::
# 94 "data/maps/ScorchedChambers/scripts.pory"
	msgbox ScorchedChambers_Camper_Text_0, MSGBOX_NPC
	return


ScorchedChambers_Hiker_Text_0:
# 6 "data/maps/ScorchedChambers/scripts.pory"
	.string "I like caves, but boy this one is hard to\n"
	.string "be in.$"

ScorchedChambers_Hiker_Text_1:
# 7 "data/maps/ScorchedChambers/scripts.pory"
	.string "I think I need to get fresh air...$"

ScorchedChambers_Hiker_Text_2:
# 9 "data/maps/ScorchedChambers/scripts.pory"
	.string "The heat in here is something else...$"

ScorchedChambers_Picnicker_Text_0:
# 16 "data/maps/ScorchedChambers/scripts.pory"
	.string "I regret coming in here with such thick\n"
	.string "clothing.$"

ScorchedChambers_Picnicker_Text_1:
# 17 "data/maps/ScorchedChambers/scripts.pory"
	.string "I think my Pokemon have heatstroke...$"

ScorchedChambers_Picnicker_Text_2:
# 19 "data/maps/ScorchedChambers/scripts.pory"
	.string "I wish I could stick my head into a\n"
	.string "fridge right now.$"

ScorchedChambers_Guitarist_Text_0:
# 26 "data/maps/ScorchedChambers/scripts.pory"
	.string "We find our greatest tunes in the face\n"
	.string "of adversity.$"

ScorchedChambers_Guitarist_Text_1:
# 27 "data/maps/ScorchedChambers/scripts.pory"
	.string "That's not very rock of you...$"

ScorchedChambers_Guitarist_Text_2:
# 29 "data/maps/ScorchedChambers/scripts.pory"
	.string "My sweat is making it hard to play the\n"
	.string "notes I want.$"

ScorchedChambers_BugCatcher_Text_0:
# 36 "data/maps/ScorchedChambers/scripts.pory"
	.string "I think I came to the wrong place.$"

ScorchedChambers_BugCatcher_Text_1:
# 37 "data/maps/ScorchedChambers/scripts.pory"
	.string "Bugs and lava, not a great mix.$"

ScorchedChambers_BugCatcher_Text_2:
# 39 "data/maps/ScorchedChambers/scripts.pory"
	.string "I thought training here would be a good\n"
	.string "test for my bugs...$"

ScorchedChambers_Fisherman_Text_0:
# 46 "data/maps/ScorchedChambers/scripts.pory"
	.string "...$"

ScorchedChambers_Fisherman_Text_1:
# 47 "data/maps/ScorchedChambers/scripts.pory"
	.string "Well.$"

ScorchedChambers_Fisherman_Text_2:
# 49 "data/maps/ScorchedChambers/scripts.pory"
	.string "I don't seem to be catching very much,\n"
	.string "not sure why.$"

ScorchedChambers_BlackBelt_Text_0:
# 56 "data/maps/ScorchedChambers/scripts.pory"
	.string "SUFFERING BUILDS CHARACTER!$"

ScorchedChambers_BlackBelt_Text_1:
# 57 "data/maps/ScorchedChambers/scripts.pory"
	.string "I GOT SWEAT IN MY EYES AHHHHH!!!$"

ScorchedChambers_BlackBelt_Text_2:
# 59 "data/maps/ScorchedChambers/scripts.pory"
	.string "I think the intense heat might be\n"
	.string "impacting my mental faculties.$"

ScorchedChambers_BattleGirl_Text_0:
# 66 "data/maps/ScorchedChambers/scripts.pory"
	.string "What is that guy yelling about?$"

ScorchedChambers_BattleGirl_Text_1:
# 67 "data/maps/ScorchedChambers/scripts.pory"
	.string "...is he okay?$"

ScorchedChambers_BattleGirl_Text_2:
# 69 "data/maps/ScorchedChambers/scripts.pory"
	.string "...oh man I'm so sticky with sweat...$"

ScorchedChambers_ExpertF_Text_0:
# 76 "data/maps/ScorchedChambers/scripts.pory"
	.string "Ah, you also fell down.$"

ScorchedChambers_ExpertF_Text_1:
# 77 "data/maps/ScorchedChambers/scripts.pory"
	.string "Well, you sure are energetic.$"

ScorchedChambers_ExpertF_Text_2:
# 79 "data/maps/ScorchedChambers/scripts.pory"
	.string "I fell down this hole a while ago, but\n"
	.string "it's like a sauna in here so it's alright.$"

ScorchedChambers_ExpertM_Text_0:
# 86 "data/maps/ScorchedChambers/scripts.pory"
	.string "Oh dear I think I put my back out.$"

ScorchedChambers_ExpertM_Text_1:
# 87 "data/maps/ScorchedChambers/scripts.pory"
	.string "I'm much too old to be falling into\n"
	.string "caves...$"

ScorchedChambers_ExpertM_Text_2:
# 89 "data/maps/ScorchedChambers/scripts.pory"
	.string "I might be too sore to make my way out...$"

ScorchedChambers_Camper_Text_0:
# 94 "data/maps/ScorchedChambers/scripts.pory"
	.string "Apparently you can jump down from here,\nbut it looks a little high for me...$"
