OchreVale_Indoor_House1_MapScripts::
	.byte 0


OchreVale_Indoor_House1_OldMan::
# 4 "data/maps/OchreVale_Indoor_House1/scripts.pory"
	lockall
# 5 "data/maps/OchreVale_Indoor_House1/scripts.pory"
	msgbox OchreVale_Indoor_House1_OldMan_Text_0, MSGBOX_NPC
# 6 "data/maps/OchreVale_Indoor_House1/scripts.pory"
	releaseall
	return


OchreVale_Indoor_House1_LittleBoy::
# 10 "data/maps/OchreVale_Indoor_House1/scripts.pory"
	lockall
# 11 "data/maps/OchreVale_Indoor_House1/scripts.pory"
	msgbox OchreVale_Indoor_House1_LittleBoy_Text_0, MSGBOX_NPC
# 12 "data/maps/OchreVale_Indoor_House1/scripts.pory"
	releaseall
	return


OchreVale_Indoor_House1_OldMan_Text_0:
# 5 "data/maps/OchreVale_Indoor_House1/scripts.pory"
	.string "My son is helping out the scientists\n"
	.string "working on the quarry research, so I'm\l"
	.string "helping by looking after my grandson.$"

OchreVale_Indoor_House1_LittleBoy_Text_0:
# 11 "data/maps/OchreVale_Indoor_House1/scripts.pory"
	.string "I heard theres something in the dirt in\n"
	.string "that big hole!$"
