SpringwoodCity_Indoor_3_MapScripts::
	.byte 0


SpringwoodCity_Indoor_3_OldMan::
# 4 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	lockall
# 5 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	msgbox SpringwoodCity_Indoor_3_OldMan_Text_0
# 6 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	releaseall
	return


SpringwoodCity_Indoor_3_OldMan2::
# 10 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	lockall
# 11 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	msgbox SpringwoodCity_Indoor_3_OldMan2_Text_0
# 12 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	releaseall
	return


SpringwoodCity_Indoor_3_OldWoman::
# 16 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	lockall
# 17 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	msgbox SpringwoodCity_Indoor_3_OldWoman_Text_0, MSGBOX_NPC
# 18 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	releaseall
	return


SpringwoodCity_Indoor_3_OldWoman2::
# 22 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	lockall
# 23 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	msgbox SpringwoodCity_Indoor_3_OldWoman2_Text_0, MSGBOX_NPC
# 24 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	releaseall
	return


SpringwoodCity_Indoor_3_OldMan_Text_0:
# 5 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	.string "Can't you see that Ghost is the\n"
	.string "superior type?$"

SpringwoodCity_Indoor_3_OldMan2_Text_0:
# 11 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	.string "You're wrong, Normal is better!$"

SpringwoodCity_Indoor_3_OldWoman_Text_0:
# 17 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	.string "Those old fools keep arguing over which\n"
	.string "type is better. I don't think they've\l"
	.string "realised that the types can't even\l"
	.string "interact.$"

SpringwoodCity_Indoor_3_OldWoman2_Text_0:
# 23 "data/maps/SpringwoodCity_Indoor_3/scripts.pory"
	.string "You would think they'd grow tired of it\n"
	.string "after 50 years...$"
