SpringwoodCity_Indoor_1_1F_MapScripts::
	.byte 0


SpringwoodCity_Indoor_1_1F_LittleGirl::
# 4 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	lockall
# 5 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	msgbox SpringwoodCity_Indoor_1_1F_LittleGirl_Text_0, MSGBOX_NPC
# 6 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	releaseall
	return


SpringwoodCity_Indoor_1_1F_LittleBoy::
# 10 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	lockall
# 11 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	msgbox SpringwoodCity_Indoor_1_1F_LittleBoy_Text_0, MSGBOX_NPC
# 12 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	releaseall
	return


SpringwoodCity_Indoor_1_1F_LittleBoy2::
# 16 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	lockall
# 17 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	msgbox SpringwoodCity_Indoor_1_1F_LittleBoy2_Text_0, MSGBOX_NPC
# 18 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	releaseall
	return


SpringwoodCity_Indoor_1_1F_OldWoman::
# 22 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	lockall
# 23 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	msgbox SpringwoodCity_Indoor_1_1F_OldWoman_Text_0, MSGBOX_NPC
# 24 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	releaseall
	return


SpringwoodCity_Indoor_1_1F_OldMan::
# 28 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	lockall
# 29 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	msgbox SpringwoodCity_Indoor_1_1F_OldMan_Text_0, MSGBOX_NPC
# 30 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	releaseall
	return


SpringwoodCity_Indoor_1_1F_LittleGirl_Text_0:
# 5 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	.string "I'm lucky that Mr and Mrs Beauloaf are\n"
	.string "here to look after me!$"

SpringwoodCity_Indoor_1_1F_LittleBoy_Text_0:
# 11 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	.string "My sister left saying she was going to\n"
	.string "be a cool Pokemon trainer! I hope I get\l"
	.string "to hear from her soon!$"

SpringwoodCity_Indoor_1_1F_LittleBoy2_Text_0:
# 17 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	.string "We like it here, the Beauloafs give us\n"
	.string "heaps of food!$"

SpringwoodCity_Indoor_1_1F_OldWoman_Text_0:
# 23 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	.string "These poor kids don't have anyone to\n"
	.string "look after them, so my husband and I\l"
	.string "take in any we find.$"

SpringwoodCity_Indoor_1_1F_OldMan_Text_0:
# 29 "data/maps/SpringwoodCity_Indoor_1_1F/scripts.pory"
	.string "Being a Pokemon Trainer isn't for\n"
	.string "everyone. Some folks end up leaving\l"
	.string "behind more than they should when they\l"
	.string "visit new places.$"
